baseURL: https://mpdesouza.com
theme: PaperMod
title: Marcos' Blog

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-LWD0KKCW2G

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production
  author: Marcos Paulo de Souza
  copyright: 2020-{{ YEAR }}

  defaultTheme: auto
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  homeInfoParams:
    Title: "Hi, I'm Marcos"
    Content: "Welcome to my personal homepage"

  socialIcons:
    - name: linkedin
      url: https://www.linkedin.com/in/marcospsouza/
    - name: github
      url: https://github.com/marcosps
    - name: twitter
      url: https://twitter.com/omarcossouza

menu:
  main:
  - name: Home
    identifier: home
    weight: 10
    url: /
  - name: About Me
    identifier: about
    weight: 20
    url: /about-me/

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    ntabWidth: 4
